services:
  postgres:
    container_name: question-answer-pg
    image: postgres
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
